MyFirstMVC/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstMVC.Models
{
    public class Company
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Укажи название телефона")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Длина названия от 1 до 50")]
        [Remote(action: "ValidateName", controller: "Validation", ErrorMessage = "Не ругайся")]
        public string Name { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        public DateTime FoundationDate { get; set; }

        public IEnumerable<Phone> Phones { get; set; }
    }
}

MyFirstMVC/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFirstMVC.Models;
using MyFirstMVC.ViewModels;

namespace MyFirstMVC.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // GET
        public ActionResult Index()
        {
            IEnumerable<Company> companies = _context.Companies.OrderBy(s => s.Name);
            return View(companies);
        }
        
        // GET: Phones/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Phones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,FoundationDate")] Company company)
        {
            List<Company> companies = _context.Companies.ToList();

            foreach (Company company1 in companies)
            {
                if (company.Name == company1.Name)
                {
                    ModelState.AddModelError("Name", "Такое имя уже существует");
                }
            }
            
            if (company.FoundationDate > DateTime.Now)
            {
                ModelState.AddModelError("FoundationDay", "Компания не может быть основана в будущем");
            }
            
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }
        
        // GET: Phones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,FoundationDay")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }
            
            List<Company> companies = _context.Companies.ToList();

            foreach (Company company1 in companies)
            {
                if (company.Name == company1.Name)
                {
                    ModelState.AddModelError("Name", "Такое имя ужесуществует");
                }
            }
            
            if (company.FoundationDate > DateTime.Now)
            {
                ModelState.AddModelError("FoundationDay", "Компания не может быть основана в будущем");
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!companyExist(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        
        private bool companyExist(int companyId)
        {
            return _context.Companies.Any(e => e.Id == companyId);
        }
    }
}

MyFirstMVC/Views/Companies/Create.cshtml
@model MyFirstMVC.Models.Company

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Companies" asp-antiforgery="true">
            <div asp-validation-summary="None" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoundationDay" class="control-label"></label>
                <input asp-for="FoundationDay" class="form-control" />
                <span asp-validation-for="FoundationDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstMVC/Views/Companies/Edit.cshtml
@model MyFirstMVC.Models.Company

@{
    ViewData["Title"] = $"Редактирование {Model.Name}";
}

<h2>Edit</h2>

<h4>Phone</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoundationDate" class="control-label"></label>
                <input asp-for="FoundationDate" class="form-control" />
                <span asp-validation-for="FoundationDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstMVC/Views/Companies/Index.cshtml
@model IEnumerable<Company>

@{

    ViewData["Title"] = "Companies";

}

<br />
<a asp-action="Create">Создать</a>
@using (Html.BeginForm("Index", "Companies", FormMethod.Get))


{<br />}

<table class="table table-bordered">

    @foreach (Company p in Model)
    {
        <tr>
            <td>@p.Name</td>
            <td>@p.Email</td>
            <td>@p.FoundationDate</td>
            <td><a asp-action="Edit" asp-route-id="@p.Id">Edit</a></td>
        </tr>

    }

</table>